version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: 
        name: Running tests
        command: make test
workflows:
  version: 2
  workflow:
    jobs:
    - build
