version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache: {}
    - run: {}
      name: Setup Dependencies
      command: npm install
workflows:
  version: 2
  workflow:
    jobs:
    - build
