version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: 
        name: Building App
        command: npm run build
workflows:
  version: 2
  workflow:
    jobs:
    - build
